spring:
  application:
    name: eureka-server

---
spring:
  profiles: zone2
eureka:
  instance:
    hostname: localhost
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
server:
  port: ${PORT:8761}

---
spring:
  profiles: zone1
eureka:
  instance:
    hostname: zone1
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
server:
  port: ${PORT:8762}

---
spring:
  profiles: zone3
eureka:
  instance:
    hostname: zone3
    metadataMap:
      zone: zone3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
server:
  port: ${PORT:8763}